config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

  # autenticate user before go
  authenticate :user do
    resources :users, only: %i(update destroy)
  end

  authenticated :user do
    root 'home#index', as: :root
  end
  unauthenticated :user do
    root 'landing#index', as: :landing_root
  end

  # capture all non-existing routes
  get '*any', via: :all, to: redirect('/404'), constraints: -> (req) { !req.fullpath.start_with?('/rails') }
end

app/models/concerns/htmlable.rb
module Htmlable
  extend ActiveSupport::Concern

  def html_id
    [self.class.name.parameterize, id].join('-')
  end
end

app/models/concerns/nameable.rb
module Nameable
  extend ActiveSupport::Concern

  included do
    scope :by_name, -> { order(name: :asc) }
  end

  def to_s
    name.present? ? name : id
  end
end

app/models/concerns/timestampable.rb
module Timestampable
  extend ActiveSupport::Concern

  included do
    scope :by_created_at_asc,   -> { order(created_at: :asc) }
    scope :by_created_at_desc,  -> { order(created_at: :desc) }
    scope :by_created_at,       -> { by_created_at_desc }
    scope :by_updated_at,       -> { order(updated_at: :desc) }
    scope :oldest_first,        -> { by_created_at_asc }
    scope :newest_first,        -> { by_created_at_desc }
    scope :fresh_first,         -> { by_updated_at }
    scope :recent,              -> (limit) { newest_first.limit(limit) }
  end
end

app/controllers/concerns/devise.rb
module Concerns
  module Devise
    extend ActiveSupport::Concern

    included do
      helper_method :logged_in?, :signed_in?
      helper_method :my, :me

      # alias for devise methods
      alias_method :my, :current_user
      alias_method :me, :current_user
      # alias for devise methods
      alias_method :signed_in?, :user_signed_in?
      alias_method :logged_in?, :user_signed_in?
    end
  end
end

app/controllers/concerns/i18n.rb
module Concerns
  module I18n
    extend ActiveSupport::Concern

    included do
      before_action :set_locale
    end

    protected

    def set_locale
      ::I18n.locale = params[:locale] || ::I18n.default_locale
    end
  end
end

app/controllers/concerns/layout.rb
module Layout
  extend ActiveSupport::Concern

  included do
    # don't render layout on xhr request
    # (ex. via ajax $(...).load(...) call)
    layout :choose_layout
  end

  protected

  def choose_layout
    return false    if request.xhr?
    return 'devise' if devise_controller? && !user_signed_in?
    'application'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def update
    info = { alert: t('.error') }
    # update user object
    info = { notice: t('.updated') } if current_user.update(user_params)
    # redirect with info or error message
    redirect_to(edit_user_registration_path, info)
  end

  def destroy
    current_user.destroy!
    redirect_to(landing_root_path, notice: t('.deleted'))
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/btn_helper.rb
module BtnHelper
  def login_btn
    render partial: 'application/btn/login'
  end

  def back_btn
    render partial: 'application/btn/back'
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return unless devise_error_messages?

    # sentence = I18n.t('errors.messages.not_saved',
    #   count: resource.errors.count,
    #   resource: resource.class.model_name.human.downcase)

    render partial: 'form_errors', locals: { errors: resource.errors }
  end

  def devise_error_messages?
    !resource.errors.empty?
  end
end

app/helpers/form_helper.rb
module FormHelper
  def show_form_errors_if_any(model)
    return if model.blank? || model.errors.blank?

    render 'form_errors', errors: model.errors
  end
end

app/helpers/layout_helper.rb
module LayoutHelper
  def layout_body_css_class
    styles = []
    styles << 'devise'    if devise_controller?
    styles << 'with_nav'  if show_top_nav?

    # return styles string
    styles.join ' '
  end
end

app/helpers/nav_helper.rb
module NavHelper
  def show_top_nav?
    user_signed_in?
  end

  def nav_element(locals)
    return if locals.blank?
    render partial: 'nav/element', locals: locals
  end
end

app/views/application/_empty.html.erb
<%% cache [local_assigns[:info], local_assigns[:disable_back]] do %>
  <div class="jumbotron jumbotron-empty empty text-center">
    <p class="lead"><%%= local_assigns[:info] %></p>
    <%%= back_btn unless local_assigns[:disable_back].present? %>
  </div>
<%% end %>

app/views/application/_form_errors.html.erb
<%% if local_assigns[:errors] %>
  <div class="alert alert-danger" role="alert">
    <strong><%%= t '.header' %></strong>&nbsp;
    <%%= t '.info' %>
    <ul>
      <%% errors.full_messages.each do |message| %>
        <li><%%= message %></li>
      <%% end %>
    </ul>
  </div>
<%% end %>

app/views/application/_header.html.erb
<%% cache [local_assigns[:header], local_assigns[:lead], local_assigns[:btn]] do %>
  <div class="page-header">
    <h1 class="<%%= 'clearfix' if local_assigns[:btn].present? %>">
      <%%= local_assigns[:header] %>
      <%% if local_assigns[:btn].present? %>
        <span class="pull-right">
          <%%= local_assigns[:btn] %>
        </span>
      <%% end %>
    </h1>
    <%% if local_assigns[:lead].present? %>
      <p class="lead"><%%= local_assigns[:lead] %></p>
    <%% end %>
  </div>
<%% end %>

app/views/application/btn/_back.html.erb
<%% cache do %>
  <%%= link_to t('back'), :back, class: 'btn btn-default' %>
<%% end %>

app/views/application/btn/_login.html.erb
<%% cache do %>
  <%%= link_to t('login'), main_app.new_user_session_path, class: 'btn btn-success btn-login' %>
<%% end %>

app/views/flash/_message.html.erb
<%% cache [name, message] do %>
  <div class="alert <%%= name == 'alert' ? 'alert-danger' : 'alert-info' %> alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
      <span class="sr-only"><%%= t 'flash.close' %></span>
    </button>
    <strong><%%= t "flash.#{name}" %></strong> <%%= raw message %>
  </div>
<%% end %>

app/views/flash/_notifications.html.erb
<%% flash.each do |name, message| %>
  <%%= render partial: 'flash/message', locals: { name: name, message: message } %>
<%% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/landing/index.html.erb
<h1>Landing#index</h1>
<p>Find me in app/views/landing/index.html.erb</p>
<%%= login_btn %>

app/views/layouts/application.html.erb
<%% content_for :content do %>
  <%%= render partial: 'nav/top' if show_top_nav? %>
  <div class="container">
    <%%= render partial: 'flash/notifications' if flash.present? %>
    <%%= yield %>
  </div>
<%% end %>
<%%= render template: 'layouts/base' %>

app/views/layouts/base.html.erb
<!DOCTYPE html>
<html lang="<%%= I18n.locale %>">
<head>
  <title><%%= t 'app.name' %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%%= stylesheet_link_tag '//fonts.googleapis.com/css?family=Lato:400,700&subset=latin,latin-ext', media: 'all' %>
  <%%= stylesheet_link_tag '//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css', media: 'all' %>
  <%%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css', media: 'all' %>
  <%%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
  <%%= yield(:stylesheets) %>
  <%%= csrf_meta_tags %>
  <%%#= action_cable_meta_tag %>
</head>
<body class="<%%= layout_body_css_class %>">
  <%%= content_for?(:content) ? yield(:content) : yield %>
  <%%= yield(:js_libraries) %>
  <%%= javascript_include_tag '//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js' %>
  <%%= javascript_include_tag '//netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js' %>
  <%%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
</body>
</html>

app/views/layouts/devise.html.erb
<%% content_for :content do %>
  <div class="container">
    <%%= render partial: 'flash/notifications' if flash.present? %>
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3">
        <div class="jumbotron">
          <%%= yield %>
        </div>
      </div>
    </div>
  <div>
<%% end %>
<%%= render template: 'layouts/base' %>

app/views/nav/_element.html.erb
<%% cache [name, path, current_page?(path), local_assigns[:id], local_assigns[:badge]] do %>
  <li class="<%%= 'active' if current_page?(path) %>" id="<%%= local_assigns[:id] %>">
    <%%= link_to path do %>
      <%%= name %>
      <%% if local_assigns[:badge].to_i > 0 %>
        <span class="badge"><%%= local_assigns[:badge] %></span>
      <%% end %>
    <%% end %>
  </li>
<%% end %>

app/views/nav/_header.html.erb
<%% cache do %>
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
      <span class="sr-only"><%%= t '.toggle' %></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%%= link_to t('app.name'), root_path, class: 'navbar-brand' %>
  </div>
<%% end %>

app/views/nav/_logout.html.erb
<%% cache do %>
  <li>
    <%%= link_to t('logout'), destroy_user_session_path, method: :delete, class: 'logout' %>
  </li>
<%% end %>

app/views/nav/_top.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <%%= render partial: 'nav/header' %>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
        <%%= nav_element name: t('.dashboard'), path: root_path %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%%= render partial: 'nav/logout' %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/_form.html.erb
<%%= form_for(current_user, html: { method: :put, multipart: true }) do |f| %>
  <%%= show_form_errors_if_any(current_user) %>
  <div class="form-group">
    <%%= f.label :name, class: 'control-label' %>
    <%%= f.text_field :name, autofocus: true, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%%= f.submit t('.update_account'), class: 'btn btn-success' %>
  </div>
<%% end %>

app/views/users/shared/_links.html.erb
<div class="links">
  <div class="row">
    <div class="col-xs-12 col-sm-6 text-center">
      <%% if controller_name != 'sessions' %>
        <%%= link_to t('login'), new_session_path(resource_name), class: 'btn btn-block btn-success' %>
      <%% else %>
        <%%= link_to t('register'), new_registration_path(resource_name), class: 'btn btn-block btn-info' %>
      <%% end %>
    </div>
    <div class="col-xs-12 col-sm-6 text-center">
      <%% if devise_mapping.recoverable? && controller_name != 'passwords' %>
        <%%= link_to t('forgot_password'), new_password_path(resource_name), class: 'btn btn-block btn-default' %>
      <%% else %>
        <%% if devise_mapping.registerable? && controller_name != 'registrations' %>
          <%%= link_to t('register'), new_registration_path(resource_name), class: 'btn btn-block btn-info' %>
        <%% end %>
      <%% end %>
    </div>
  </div>
</div>

app/views/users/shared/_login_with.html.erb
<%% cache resource_name do %>
  <div class="login-with">
    <div class="row">
      <div class="col-xs-12 text-center">
        <%%= link_to(omniauth_authorize_path(resource_name, :facebook), class: 'btn facebook-login') do %>
          <i class="fa fa-facebook-square"></i><%%= t '.facebook' %>
        <%% end %>
      </div>
    </div>
  </div>
<%% end %>